<a href="https://colab.research.google.com/github/arosha27/00-FundamentsOfPyTorch/blob/main/pyTorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pyTorch Fundamentals
Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/
discussions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [76]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
- Creating tensors

**Scalar**

In [77]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [78]:
scalar.ndim

0

In [79]:
scalar.shape

torch.Size([])

In [80]:
scalar.item()

7

**vector**

In [81]:
#vectors
vector = torch.tensor([3,7])
vector

tensor([3, 7])

In [82]:
vector.ndim

1

In [83]:
vector.shape

torch.Size([2])

In [84]:
vector[0]

tensor(3)

In [85]:
vector[1]

tensor(7)

**MATRIX**

In [86]:
MATRIX = torch.tensor([[12,16],
                       [15,19],
                       [45,90]])
MATRIX

tensor([[12, 16],
        [15, 19],
        [45, 90]])

In [87]:
MATRIX.ndim

2

In [88]:
MATRIX.shape

torch.Size([3, 2])

In [89]:
MATRIX[0]

tensor([12, 16])

**Tensor**

In [90]:
TENSOR = torch.tensor([[[12,29],[34,90],[90,68]]])
TENSOR

tensor([[[12, 29],
         [34, 90],
         [90, 68]]])

In [91]:
TENSOR.ndim

3

In [92]:
TENSOR.shape

torch.Size([1, 3, 2])

In [93]:
TENSOR[0]

tensor([[12, 29],
        [34, 90],
        [90, 68]])

In [94]:
#another example
TENSOR = torch.tensor([[[[1,2],[2,9]]]])
TENSOR.ndim


4

In [95]:
TENSOR.shape

torch.Size([1, 1, 2, 2])

In [96]:
TENSOR[0]

tensor([[[1, 2],
         [2, 9]]])