<a href="https://colab.research.google.com/github/arosha27/00-FundamentsOfPyTorch/blob/main/pyTorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pyTorch Fundamentals
Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/
discussions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [106]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
- Creating tensors (Basic building block of data representation i.e Tensors in deep learning)

**Scalar**

In [107]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [108]:
scalar.ndim

0

In [109]:
scalar.shape

torch.Size([])

In [110]:
scalar.item()

7

**vector**

In [111]:
#vectors
vector = torch.tensor([3,7])
vector

tensor([3, 7])

In [112]:
vector.ndim

1

In [113]:
vector.shape

torch.Size([2])

In [114]:
vector[0]

tensor(3)

In [115]:
vector[1]

tensor(7)

**MATRIX**

In [116]:
MATRIX = torch.tensor([[12,16],
                       [15,19],
                       [45,90]])
MATRIX

tensor([[12, 16],
        [15, 19],
        [45, 90]])

In [117]:
MATRIX.ndim

2

In [118]:
MATRIX.shape

torch.Size([3, 2])

In [119]:
MATRIX[0]

tensor([12, 16])

**Tensor**

In [120]:
TENSOR = torch.tensor([[[12,29],[34,90],[90,68]]])
TENSOR

tensor([[[12, 29],
         [34, 90],
         [90, 68]]])

In [121]:
TENSOR.ndim

3

In [122]:
TENSOR.shape

torch.Size([1, 3, 2])

In [123]:
TENSOR[0]

tensor([[12, 29],
        [34, 90],
        [90, 68]])

In [124]:
#another example
TENSOR = torch.tensor([[[[1,2],[2,9]]]])
TENSOR.ndim


4

In [125]:
TENSOR.shape

torch.Size([1, 1, 2, 2])

In [126]:
TENSOR[0]

tensor([[[1, 2],
         [2, 9]]])

**Random** **tensor**
why we need to create random tensors?
- Ramdom tensors are very important as many neaural networks uses a full of random numbers in the tensors to get trained at first and then adjust them and update those numbers

`
Start with random numbers -> look at data -> update random numbers -> look at the data -> update the random numbers
`

In [127]:
#create a random tensor of shape or size(2,4)
random_tensor=torch.rand(1,2,4)
random_tensor
#number of complete outside bracket inside the bracket shows the dimension

tensor([[[0.9307, 0.2040, 0.5686, 0.6006],
         [0.0486, 0.8703, 0.1533, 0.0219]]])

In [128]:
#almost any data can be converted to tensors
#create a random tensor with the same shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,244,244)) # color chennel, height , width
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 244, 244]), 3)

In [129]:
random_image_size_tensor.dtype
#by default all the tensors datatype is float unless explicitly changed.

torch.float32

**zeros tensors**

In [130]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [131]:
zeroes_tensors = torch.zeros(2,2,3)
zeroes_tensors.dtype , zeroes.ndim

(torch.float32, 2)

In [132]:
ones_tensors = torch.ones(2,5)
ones_tensors

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a range of tensors
**arange()**

In [133]:
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
one_to_ten.ndim


1

In [135]:
random_range=torch.arange(start=10,end=1000,step=100)
random_range

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

**Tensors-like** :
 - when you want to create a tensor without explicitly defining its shape .then tensor-like method is used . Its like create a tensor of shape of some input tensor


In [136]:
one_to_ten.shape

torch.Size([9])

In [137]:

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros.shape

torch.Size([9])

In [138]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

Three types of error we mostly encounter when dealing with the data type of the tensors:

- tensors datatype is not right
- tensors shape is not right
- the device on which tensors are running is not right


In [139]:
float_32_tensor = torch.tensor([2.0,7.0,9.0],
                               dtype=None, #what datatype our tensor do have
                               device=None, #what device our tensor will run on
                               requires_grad=False #whether or not tensor will track the gradients
                               )
float_32_tensor.dtype


torch.float32

In [140]:
# torch.float32 => full precision
# torch.float16 => half precision
# torch.float64 => double precision
#we can convert 32 bit to 16 bit by this , making them fast


float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([2., 7., 9.], dtype=torch.float16)

**Checking compatibility of tensors by adding or multiplying different dtypes tensors**

In [141]:
#multiplying 16 bits tensor with 32 bits tensor

float_16_tensor * float_32_tensor

tensor([ 4., 49., 81.])

In [142]:
#Multiplying 32 bits int tensor with 32 bits float TensorSequenceType

#firt creating 32bits integer tensor
int_32_tensor = torch.tensor([2,9,7],
                             dtype = torch.int32)
int_32_tensor.dtype

int_32_tensor * float_32_tensor


tensor([ 4., 63., 63.])

In [143]:
#Multiplying long tensor with 32 bits float Tensor

#firt creating 32bits integer tensor
int_32_tensor = torch.tensor([2,9,7],
                             dtype = torch.long)
int_32_tensor.dtype

int_32_tensor * float_32_tensor


tensor([ 4., 63., 63.])

**Tensors Attribute**:
 - for getting information from tensors
  - dtype
  - shape
  - device

In [144]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.1531, 0.4593, 0.9938],
        [0.0607, 0.3456, 0.5290]])

In [145]:
#getting information about the tensors

print(random_tensor)
print(f"shape of random_tensor = {random_tensor.shape}")
print(f"device on which random_tensor is reated = {random_tensor.device}")
print(f"datatype of the randam_tensor = {random_tensor.dtype}")

tensor([[0.1531, 0.4593, 0.9938],
        [0.0607, 0.3456, 0.5290]])
shape of random_tensor = torch.Size([2, 3])
device on which random_tensor is reated = cpu
datatype of the randam_tensor = torch.float32


# Tensor Operations: Manipulating tensors
Tensor operations Include:
- Addition
- Subtraction
- Multiplication(element-wise)
- Division
- Matrix Multiplication

In [146]:
general_tensor = torch.tensor([2,5,10])
general_tensor + 2
#alternative method
#torch.add(general_tensor,2)

tensor([ 4,  7, 12])

In [147]:
general_tensor * 10
#alternative method using built in function
#torch.mul(general_tensor ,10)

tensor([ 20,  50, 100])

In [148]:
general_tensor - 10
#alternative method using built in method
torch.sub(general_tensor,10)


tensor([-8, -5,  0])

**Matrix** **Multiplication**

There are two ways of multiplication in neural networks or deep learning

- Element wise multiplication
- Matrix Multiplication(dot product)

In [149]:
general_tensor

tensor([ 2,  5, 10])

In [150]:
#element wise multiplication
print(general_tensor ,"*",general_tensor)
print(general_tensor * general_tensor)

tensor([ 2,  5, 10]) * tensor([ 2,  5, 10])
tensor([  4,  25, 100])


In [151]:
#matrix multipliaction
torch.matmul(general_tensor,general_tensor)

tensor(129)

In [152]:
#manual matrix multiplication
#2*2 +5*5 + 10*10
%%time
value=0
for i in range(len(general_tensor)):
  value = value + general_tensor[i] * general_tensor[i]
print(value)

tensor(129)
CPU times: user 783 µs, sys: 0 ns, total: 783 µs
Wall time: 789 µs


In [153]:
%%time
#general_tensor @ general_tensor
torch.matmul(general_tensor , general_tensor)

CPU times: user 77 µs, sys: 12 µs, total: 89 µs
Wall time: 95.4 µs


tensor(129)

**note : built in torch methods are fast and efficient**

The most common error in the tensor multiplication is the shape error
 - for matrix multiplication:
  - the num of columns in first matrix must be equal to the number of rows in the second matrix
  - i.e inner dimensions must be equal
  - (2,3) @ (2,3) won't work
  - (3,2) @ (2,3) will work
  - (3,4) @ (4,3) => (3,3)

In [154]:
torch.matmul(torch.rand(3,4) , torch.rand(4,3))

tensor([[0.7965, 0.6526, 0.5834],
        [1.2634, 1.2921, 0.8494],
        [1.0510, 1.1108, 1.2090]])

**How to deal with shape errors in matrix multiplication**
 - take the transpose of tge any of the matrix
 - transpose means changing the axis . i.e changing rows into coulmnn or coulmns into rowns

In [155]:
tensor_A = torch.tensor([[1,5],[3,9],[8,0]])
tensor_A.shape

torch.Size([3, 2])

In [156]:
tensor_B = torch.tensor([[3,9],[9,7],[5,8]])
tensor_B.shape

torch.Size([3, 2])

In [157]:
#as inner dimensions are not equaal , it will throw an error on running

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [158]:
#in order to make the shape compatible , take the transpose of any tensor
Transpose_tensor_A= tensor_A.T  #(2,3)

In [159]:
torch.matmul(Transpose_tensor_A, tensor_B)

tensor([[ 70,  94],
        [ 96, 108]])

In [160]:
print(f"tensor_A.shape:{tensor_A.shape} and tensor_B.shape: {tensor_B.shape}")
print("inner dimensions are not equal , thus mulptication is not possible")
print(f"tensor_A.shape :{tensor_A.shape} and tensor_B.transpose.shape: {tensor_B.T.shape}")
print("inner dimensions are equal , thus mulptication is possible")
print(f"The output matrix of outer dimension shape is after matrix multipliaction = {torch.mm(tensor_A,tensor_B.T)}")

tensor_A.shape:torch.Size([3, 2]) and tensor_B.shape: torch.Size([3, 2])
inner dimensions are not equal , thus mulptication is not possible
tensor_A.shape :torch.Size([3, 2]) and tensor_B.transpose.shape: torch.Size([2, 3])
inner dimensions are equal , thus mulptication is possible
The output matrix of outer dimension shape is after matrix multipliaction = tensor([[48, 44, 45],
        [90, 90, 87],
        [24, 72, 40]])


## Tensor Aggregation
- finding the min , max , mean, sum,etc

In [169]:
rand_tensor = torch.rand(2,4)

In [162]:
Tensor

tensor([[0.0683, 0.0149, 0.4642, 0.7569],
        [0.0968, 0.9383, 0.8425, 0.4555]])

In [171]:
#sum
rand_tensor.sum() , torch.sum(rand_tensor)

(tensor(3.7229), tensor(3.7229))

In [170]:
#min
rand_tensor.min() , torch.min(rand_tensor)

(tensor(0.0223), tensor(0.0223))

In [173]:
#max
rand_tensor.max() , torch.max(rand_tensor)

(tensor(0.8289), tensor(0.8289))

In [180]:
#mean => mean function only works on float and complex values . As long int is given as input that's why it is throwing an error
int_values_tensor = torch.tensor([2,6,9,10],dtype=torch.int64)
# int_values_tensor.type(torch.float32).mean() #alternative method
torch.mean(int_values_tensor.type(torch.float16))

tensor(6.7500, dtype=torch.float16)

**positional min and max using argmax and argmin**

In [184]:
#argmin => will provide us the position or index of the minimum value in the given torch.tensor
new_tensor = torch.arange(2,1000,90)
new_tensor

tensor([  2,  92, 182, 272, 362, 452, 542, 632, 722, 812, 902, 992])

In [185]:
rand_tensor.argmin()

tensor(0)

In [186]:
new_tensor[0] #we can find the minimum value in the tensor by using that position or index by argmin

tensor(2)

In [189]:
new_tensor.argmax() # outputs the position or index of maximum value in the tensor

tensor(11)

In [190]:
new_tensor[5]

tensor(452)

**Reshaping , stacking , sequeezing and unsequeezing tensors**

- The most common problem we encounter while working with tensors is shape incompatibility.
- To solve this error , different methods are used , some of which are as follows:
  * **Reshaping:** changing the shape of the tensor with the defined shape.
  * **view :** return a view of the input tensor in a specified shape but both the original tensor and the reshaped tensor via view are pointing to same memory location , changes in one reflects to other as well
  * **stacking** : combining the tensors in a dimention specified . By default its vertical dim=0
  * **sequeezing :** means removing the single dimension from the input array. i.e removing from double brackets to single brackets

  * **unsequeezing:**  means adding a new single dimension in the tensor i.e adding a bracket

  * **permute**: means modifying the dimensions or axis of the values in the tensors.

**reshape**()

In [199]:
x = torch.arange(2,10)
x , x.shape

(tensor([2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([8]))

In [207]:
# x_resahped = x.reshape(8,1)
# x_resahped = x.reshape(1,8)
# x_reshaped = x.reshape(2,4)
#all these are possible in which shape is comaptible
#the shape of the new modified tensor should be such way that after multiplying them , it should give the size value of the original tensor
# original tensor = 8 , new tensor can be any shape that make 8 on multiplying
x_reshaped = x.reshape(4,2)


In [224]:
print(f"original tensor is {x} with shape {x.shape}")
print("_________________________________________________")
print(f"reshaped tensor is {x_reshaped} with the shape {x_reshaped.shape}")

original tensor is tensor([2, 3, 4, 5, 6, 7, 8, 9]) with shape torch.Size([8])
_________________________________________________
reshaped tensor is tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) with the shape torch.Size([4, 2])


**view**

In [243]:
new_tensor.shape

torch.Size([12])

In [245]:
new_viewed_tensor= new_tensor.view(4,3)
new_tensor.shape


torch.Size([12])

In [255]:

print(f"new_tensor is {new_tensor} with shape {new_tensor.shape}")
print("_________________________________________________")
print(f"view of the new_tensor is {new_viewed_tensor} with shape {new_viewed_tensor.shape}")

new_tensor is tensor([  2,  92,  17, 272, 362, 452, 542, 632, 722, 812, 902, 992]) with shape torch.Size([12])
_________________________________________________
view of the new_tensor is tensor([[  2,  92,  17],
        [272, 362, 452],
        [542, 632, 722],
        [812, 902, 992]]) with shape torch.Size([4, 3])


In [252]:
new_tensor[2]=17
new_viewed_tensor[0][2]

#changes done in one also reflects in the other . this is because as both are pointing to same memory lacation

tensor(17)

**Stacking**

In [266]:
stacked_tensors = torch.stack([x,x,x],dim=1)
#dim=0 row wise stacking in vertical manner
#dim=1 column wise stacking in horizontal manner
stacked_tensors


tensor([[ 2,  2,  2],
        [19, 19, 19],
        [19, 19, 19],
        [19, 19, 19],
        [ 6,  6,  6],
        [19, 19, 19],
        [ 8,  8,  8],
        [19, 19, 19]])

**Sequeeze**

In [300]:
Tensor = torch.tensor([[[2,9],[2,0],[4,5]]])
Tensor.shape
print(f"Before squeezing: {Tensor} with shape {Tensor.shape}")

Before squeezing: tensor([[[2, 9],
         [2, 0],
         [4, 5]]]) with shape torch.Size([1, 3, 2])


In [304]:
squeezed= torch.squeeze(Tensor)
print(f"After squeezing: {squeezed} with shape {squeezed.shape}")

After squeezing: tensor([[2, 9],
        [2, 0],
        [4, 5]]) with shape torch.Size([3, 2])


**Unsqueezing**

In [314]:
squeezed , squeezed.shape


(tensor([[2, 9],
         [2, 0],
         [4, 5]]),
 torch.Size([3, 2]))

In [316]:
unsqueezed = torch.unsqueeze(squeezed,1)
unsqueezed , unsqueezed.shape  # 0 dimension means add brackets as whole .ie. column wise ,while 1 dimension means adding bracket along each each row

(tensor([[[2, 9]],
 
         [[2, 0]],
 
         [[4, 5]]]),
 torch.Size([3, 1, 2]))

**permute**

In [327]:
x = torch.randn(2,3,5)
print(f"Before permutation: {x} with shape {x.shape}")
x.size()

print("________________________________________")
print("________________________________________")
permuted= torch.permute(x,(2,0,1)) #changing the 0->2 , 1->0 , 2->1
print(f"after permutation: {permuted} with shape {permuted.shape}")

Before permutation: tensor([[[-1.1212,  1.6606, -0.3821,  0.5897,  0.1732],
         [-1.2520, -0.4588,  0.3888,  2.0533,  1.7238],
         [ 2.5456, -2.5226,  0.0185, -0.6820, -0.4414]],

        [[-1.2303,  0.6589, -0.4161,  0.1748, -0.6759],
         [ 1.7761,  2.1099,  0.7680,  1.6361, -0.4813],
         [ 0.2046,  1.1726,  1.2369,  0.5373,  0.9242]]]) with shape torch.Size([2, 3, 5])
________________________________________
________________________________________
after permutation: tensor([[[-1.1212, -1.2520,  2.5456],
         [-1.2303,  1.7761,  0.2046]],

        [[ 1.6606, -0.4588, -2.5226],
         [ 0.6589,  2.1099,  1.1726]],

        [[-0.3821,  0.3888,  0.0185],
         [-0.4161,  0.7680,  1.2369]],

        [[ 0.5897,  2.0533, -0.6820],
         [ 0.1748,  1.6361,  0.5373]],

        [[ 0.1732,  1.7238, -0.4414],
         [-0.6759, -0.4813,  0.9242]]]) with shape torch.Size([5, 2, 3])


In [336]:
#Another example
#creating tensor for image

x_original = torch.rand(244,244,3) #height , width , colour chennels
x_permuted = torch.permute(x_original,(2,0,1)) #color chennels, height , width

x_original.shape , x_permuted.shape
#note x_original and x_permuted will share the same memory in the computer


(torch.Size([244, 244, 3]), torch.Size([3, 244, 244]))

In [344]:
#chnaging the ist value in x_orginal and then checking whether it is affecting the x_permuted or not

x_original[0,0,0]=10
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(10.), tensor(10.))

## Indexing

indexing with PyTorch are same as the indexing in NumPy

In [374]:
#creatting a tensor
x=torch.arange(1,90,8)
x.shape
x= x.reshape(1,4,3)
x

tensor([[[ 1,  9, 17],
         [25, 33, 41],
         [49, 57, 65],
         [73, 81, 89]]])

In [365]:
x[0]

tensor([ 1,  9, 17])

In [366]:
x[0][0]

tensor([ 1,  9, 17])

In [368]:
x[0][0][0]

tensor(1)

In [375]:
x[0][0][2]

tensor(17)

In [370]:
x[:,:,1]

tensor([[ 9, 33, 57, 81]])

In [373]:
x[0, : ,1]

tensor([ 9, 33, 57, 81])