<a href="https://colab.research.google.com/github/arosha27/00-FundamentsOfPyTorch/blob/main/pyTorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pyTorch Fundamentals
Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/
discussions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [231]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
- Creating tensors (Basic building block of data representation i.e Tensors in deep learning)

**Scalar**

In [232]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [233]:
scalar.ndim

0

In [234]:
scalar.shape

torch.Size([])

In [235]:
scalar.item()

7

**vector**

In [236]:
#vectors
vector = torch.tensor([3,7])
vector

tensor([3, 7])

In [237]:
vector.ndim

1

In [238]:
vector.shape

torch.Size([2])

In [239]:
vector[0]

tensor(3)

In [240]:
vector[1]

tensor(7)

**MATRIX**

In [241]:
MATRIX = torch.tensor([[12,16],
                       [15,19],
                       [45,90]])
MATRIX

tensor([[12, 16],
        [15, 19],
        [45, 90]])

In [242]:
MATRIX.ndim

2

In [243]:
MATRIX.shape

torch.Size([3, 2])

In [244]:
MATRIX[0]

tensor([12, 16])

**Tensor**

In [245]:
TENSOR = torch.tensor([[[12,29],[34,90],[90,68]]])
TENSOR

tensor([[[12, 29],
         [34, 90],
         [90, 68]]])

In [246]:
TENSOR.ndim

3

In [247]:
TENSOR.shape

torch.Size([1, 3, 2])

In [248]:
TENSOR[0]

tensor([[12, 29],
        [34, 90],
        [90, 68]])

In [249]:
#another example
TENSOR = torch.tensor([[[[1,2],[2,9]]]])
TENSOR.ndim


4

In [250]:
TENSOR.shape

torch.Size([1, 1, 2, 2])

In [251]:
TENSOR[0]

tensor([[[1, 2],
         [2, 9]]])

**Random** **tensor**
why we need to create random tensors?
- Ramdom tensors are very important as many neaural networks uses a full of random numbers in the tensors to get trained at first and then adjust them and update those numbers

`
Start with random numbers -> look at data -> update random numbers -> look at the data -> update the random numbers
`

In [252]:
#create a random tensor of shape or size(2,4)
random_tensor=torch.rand(1,2,4)
random_tensor
#number of complete outside bracket inside the bracket shows the dimension

tensor([[[0.4150, 0.2522, 0.8597, 0.4908],
         [0.7847, 0.1730, 0.0442, 0.0467]]])

In [253]:
#almost any data can be converted to tensors
#create a random tensor with the same shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,244,244)) # color chennel, height , width
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 244, 244]), 3)

In [254]:
random_image_size_tensor.dtype
#by default all the tensors datatype is float unless explicitly changed.

torch.float32

**zeros tensors**

In [255]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [256]:
zeroes_tensors = torch.zeros(2,2,3)
zeroes_tensors.dtype , zeroes.ndim

(torch.float32, 2)

In [257]:
ones_tensors = torch.ones(2,5)
ones_tensors

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a range of tensors
**arange()**

In [258]:
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
one_to_ten.ndim


1

In [260]:
random_range=torch.arange(start=10,end=1000,step=100)
random_range

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

**Tensors-like** :
 - when you want to create a tensor without explicitly defining its shape .then tensor-like method is used . Its like create a tensor of shape of some input tensor


In [261]:
one_to_ten.shape

torch.Size([9])

In [262]:

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros.shape

torch.Size([9])

In [263]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

Three types of error we mostly encounter when dealing with the data type of the tensors:

- tensors datatype is not right
- tensors shape is not right
- the device on which tensors are running is not right


In [264]:
float_32_tensor = torch.tensor([2.0,7.0,9.0],
                               dtype=None, #what datatype our tensor do have
                               device=None, #what device our tensor will run on
                               requires_grad=False #whether or not tensor will track the gradients
                               )
float_32_tensor.dtype


torch.float32

In [265]:
# torch.float32 => full precision
# torch.float16 => half precision
# torch.float64 => double precision
#we can convert 32 bit to 16 bit by this , making them fast


float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([2., 7., 9.], dtype=torch.float16)

**Checking compatibility of tensors by adding or multiplying different dtypes tensors**

In [266]:
#multiplying 16 bits tensor with 32 bits tensor

float_16_tensor * float_32_tensor

tensor([ 4., 49., 81.])

In [267]:
#Multiplying 32 bits int tensor with 32 bits float TensorSequenceType

#firt creating 32bits integer tensor
int_32_tensor = torch.tensor([2,9,7],
                             dtype = torch.int32)
int_32_tensor.dtype

int_32_tensor * float_32_tensor


tensor([ 4., 63., 63.])

In [268]:
#Multiplying long tensor with 32 bits float Tensor

#firt creating 32bits integer tensor
int_32_tensor = torch.tensor([2,9,7],
                             dtype = torch.long)
int_32_tensor.dtype

int_32_tensor * float_32_tensor


tensor([ 4., 63., 63.])

**Tensors Attribute**:
 - for getting information from tensors
  - dtype
  - shape
  - device

In [269]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.1764, 0.1032, 0.4936],
        [0.7317, 0.0098, 0.3562]])

In [270]:
#getting information about the tensors

print(random_tensor)
print(f"shape of random_tensor = {random_tensor.shape}")
print(f"device on which random_tensor is reated = {random_tensor.device}")
print(f"datatype of the randam_tensor = {random_tensor.dtype}")

tensor([[0.1764, 0.1032, 0.4936],
        [0.7317, 0.0098, 0.3562]])
shape of random_tensor = torch.Size([2, 3])
device on which random_tensor is reated = cpu
datatype of the randam_tensor = torch.float32


# Tensor Operations: Manipulating tensors
Tensor operations Include:
- Addition
- Subtraction
- Multiplication(element-wise)
- Division
- Matrix Multiplication

In [230]:
general_tensor = torch.tensor([2,5,10])
general_tensor + 2
#alternative method
#torch.add(general_tensor,2)

tensor([ 4,  7, 12])

In [271]:
general_tensor * 10
#alternative method using built in function
#torch.mul(general_tensor ,10)

tensor([ 20,  50, 100])

In [272]:
general_tensor - 10
#alternative method using built in method
torch.sub(general_tensor,10)


tensor([-8, -5,  0])

**Matrix** **Multiplication**

There are two ways of multiplication in neural networks or deep learning

- Element wise multiplication
- Matrix Multiplication(dot product)

In [273]:
general_tensor

tensor([ 2,  5, 10])

In [282]:
#element wise multiplication
print(general_tensor ,"*",general_tensor)
print(general_tensor * general_tensor)

tensor([ 2,  5, 10]) * tensor([ 2,  5, 10])
tensor([  4,  25, 100])


In [276]:
#matrix multipliaction
torch.matmul(general_tensor,general_tensor)

tensor(129)

In [287]:
#manual matrix multiplication
#2*2 +5*5 + 10*10
%%time
value=0
for i in range(len(general_tensor)):
  value = value + general_tensor[i] * general_tensor[i]
print(value)

tensor(129)
CPU times: user 1.44 ms, sys: 31 µs, total: 1.48 ms
Wall time: 1.36 ms


In [288]:
%%time
#general_tensor @ general_tensor
torch.matmul(general_tensor , general_tensor)

CPU times: user 0 ns, sys: 889 µs, total: 889 µs
Wall time: 588 µs


tensor(129)

**note : built in torch methods are fast and efficient**

The most common error in the tensor multiplication is the shape error
 - for matrix multiplication:
  - the num of columns in first matrix must be equal to the number of rows in the second matrix
  - i.e inner dimensions must be equal
  - (2,3) @ (2,3) won't work
  - (3,2) @ (2,3) will work
  - (3,4) @ (4,3) => (3,3)

In [300]:
torch.matmul(torch.rand(3,4) , torch.rand(4,3))

tensor([[2.0630, 1.7494, 1.9401],
        [2.0859, 1.7451, 1.9429],
        [0.9717, 0.7484, 0.9338]])

**How to deal with shape errors in matrix multiplication**
 - take the transpose of tge any of the matrix
 - transpose means changing the axis . i.e changing rows into coulmnn or coulmns into rowns

In [301]:
tensor_A = torch.tensor([[1,5],[3,9],[8,0]])
tensor_A.shape

torch.Size([3, 2])

In [302]:
tensor_B = torch.tensor([[3,9],[9,7],[5,8]])
tensor_B.shape

torch.Size([3, 2])

In [303]:
#as inner dimensions are not equaal , it will throw an error on running

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [309]:
#in order to make the shape compatible , take the transpose of any tensor
Transpose_tensor_A= tensor_A.T  #(2,3)

In [310]:
torch.matmul(Transpose_tensor_A, tensor_B)

tensor([[ 70,  94],
        [ 96, 108]])

In [317]:
print(f"tensor_A.shape:{tensor_A.shape} and tensor_B.shape: {tensor_B.shape}")
print("inner dimensions are not equal , thus mulptication is not possible")
print(f"tensor_A.shape :{tensor_A.shape} and tensor_B.transpose.shape: {tensor_B.T.shape}")
print("inner dimensions are equal , thus mulptication is possible")
print(f"The output matrix of outer dimension shape is after matrix multipliaction = {torch.mm(tensor_A,tensor_B.T)}")

tensor_A.shape:torch.Size([3, 2]) and tensor_B.shape: torch.Size([3, 2])
inner dimensions are not equal , thus mulptication is not possible
tensor_A.shape :torch.Size([3, 2]) and tensor_B.transpose.shape: torch.Size([2, 3])
inner dimensions are equal , thus mulptication is possible
The output matrix of outer dimension shape is after matrix multipliaction = tensor([[48, 44, 45],
        [90, 90, 87],
        [24, 72, 40]])


## Tensor Aggregation
- finding the min , max , mean, sum,etc