<a href="https://colab.research.google.com/github/arosha27/00-FundamentsOfPyTorch/blob/main/pyTorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pyTorch Fundamentals
Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/
discussions : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
- Creating tensors (Basic building block of data representation i.e Tensors in deep learning)

**Scalar**

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

7

**vector**

In [6]:
#vectors
vector = torch.tensor([3,7])
vector

tensor([3, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
vector[0]

tensor(3)

In [10]:
vector[1]

tensor(7)

**MATRIX**

In [11]:
MATRIX = torch.tensor([[12,16],
                       [15,19],
                       [45,90]])
MATRIX

tensor([[12, 16],
        [15, 19],
        [45, 90]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([3, 2])

In [14]:
MATRIX[0]

tensor([12, 16])

**Tensor**

In [15]:
TENSOR = torch.tensor([[[12,29],[34,90],[90,68]]])
TENSOR

tensor([[[12, 29],
         [34, 90],
         [90, 68]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 2])

In [18]:
TENSOR[0]

tensor([[12, 29],
        [34, 90],
        [90, 68]])

In [19]:
#another example
TENSOR = torch.tensor([[[[1,2],[2,9]]]])
TENSOR.ndim


4

In [20]:
TENSOR.shape

torch.Size([1, 1, 2, 2])

In [21]:
TENSOR[0]

tensor([[[1, 2],
         [2, 9]]])

**Random** **tensor**
why we need to create random tensors?
- Ramdom tensors are very important as many neaural networks uses a full of random numbers in the tensors to get trained at first and then adjust them and update those numbers

`
Start with random numbers -> look at data -> update random numbers -> look at the data -> update the random numbers
`

In [22]:
#create a random tensor of shape or size(2,4)
random_tensor=torch.rand(1,2,4)
random_tensor
#number of complete outside bracket inside the bracket shows the dimension

tensor([[[0.8296, 0.5668, 0.0701, 0.8678],
         [0.7239, 0.3848, 0.8250, 0.1424]]])

In [23]:
#almost any data can be converted to tensors
#create a random tensor with the same shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,244,244)) # color chennel, height , width
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 244, 244]), 3)

In [24]:
random_image_size_tensor.dtype
#by default all the tensors datatype is float unless explicitly changed.

torch.float32

**zeros tensors**

In [25]:
zeroes = torch.zeros(2,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
zeroes_tensors = torch.zeros(2,2,3)
zeroes_tensors.dtype , zeroes.ndim

(torch.float32, 2)

In [27]:
ones_tensors = torch.ones(2,5)
ones_tensors

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a range of tensors
**arange()**

In [28]:
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
one_to_ten.ndim


1

In [30]:
random_range=torch.arange(start=10,end=1000,step=100)
random_range

tensor([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

**Tensors-like** :
 - when you want to create a tensor without explicitly defining its shape .then tensor-like method is used . Its like create a tensor of shape of some input tensor


In [31]:
one_to_ten.shape

torch.Size([9])

In [32]:

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros.shape

torch.Size([9])

In [33]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

Three types of error we mostly encounter when dealing with the data type of the tensors:

- tensors datatype is not right
- tensors shape is not right
- the device on which tensors are running is not right


In [34]:
float_32_tensor = torch.tensor([2.0,7.0,9.0],
                               dtype=None, #what datatype our tensor do have
                               device=None, #what device our tensor will run on
                               requires_grad=False #whether or not tensor will track the gradients
                               )
float_32_tensor.dtype


torch.float32

In [35]:
# torch.float32 => full precision
# torch.float16 => half precision
# torch.float64 => double precision
#we can convert 32 bit to 16 bit by this , making them fast


float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([2., 7., 9.], dtype=torch.float16)

**Checking compatibility of tensors by adding or multiplying different dtypes tensors**

In [36]:
#multiplying 16 bits tensor with 32 bits tensor

float_16_tensor * float_32_tensor

tensor([ 4., 49., 81.])

In [37]:
#Multiplying 32 bits int tensor with 32 bits float TensorSequenceType

#firt creating 32bits integer tensor
int_32_tensor = torch.tensor([2,9,7],
                             dtype = torch.int32)
int_32_tensor.dtype

int_32_tensor * float_32_tensor


tensor([ 4., 63., 63.])

In [38]:
#Multiplying long tensor with 32 bits float Tensor

#firt creating 32bits integer tensor
int_32_tensor = torch.tensor([2,9,7],
                             dtype = torch.long)
int_32_tensor.dtype

int_32_tensor * float_32_tensor


tensor([ 4., 63., 63.])

**Tensors Attribute**:
 - for getting information from tensors
  - dtype
  - shape
  - device

In [39]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.3301, 0.4369, 0.9177],
        [0.7054, 0.9777, 0.4325]])

In [40]:
#getting information about the tensors

print(random_tensor)
print(f"shape of random_tensor = {random_tensor.shape}")
print(f"device on which random_tensor is reated = {random_tensor.device}")
print(f"datatype of the randam_tensor = {random_tensor.dtype}")

tensor([[0.3301, 0.4369, 0.9177],
        [0.7054, 0.9777, 0.4325]])
shape of random_tensor = torch.Size([2, 3])
device on which random_tensor is reated = cpu
datatype of the randam_tensor = torch.float32


# Tensor Operations: Manipulating tensors
Tensor operations Include:
- Addition
- Subtraction
- Multiplication(element-wise)
- Division
- Matrix Multiplication

In [41]:
general_tensor = torch.tensor([2,5,10])
general_tensor + 2
#alternative method
#torch.add(general_tensor,2)

tensor([ 4,  7, 12])

In [42]:
general_tensor * 10
#alternative method using built in function
#torch.mul(general_tensor ,10)

tensor([ 20,  50, 100])

In [43]:
general_tensor - 10
#alternative method using built in method
torch.sub(general_tensor,10)


tensor([-8, -5,  0])

**Matrix** **Multiplication**

There are two ways of multiplication in neural networks or deep learning

- Element wise multiplication
- Matrix Multiplication(dot product)

In [44]:
general_tensor

tensor([ 2,  5, 10])

In [45]:
#element wise multiplication
print(general_tensor ,"*",general_tensor)
print(general_tensor * general_tensor)

tensor([ 2,  5, 10]) * tensor([ 2,  5, 10])
tensor([  4,  25, 100])


In [46]:
#matrix multipliaction
torch.matmul(general_tensor,general_tensor)

tensor(129)

In [47]:
#manual matrix multiplication
#2*2 +5*5 + 10*10
%%time
value=0
for i in range(len(general_tensor)):
  value = value + general_tensor[i] * general_tensor[i]
print(value)

tensor(129)
CPU times: user 221 µs, sys: 1.04 ms, total: 1.26 ms
Wall time: 2.29 ms


In [48]:
%%time
#general_tensor @ general_tensor
torch.matmul(general_tensor , general_tensor)

CPU times: user 67 µs, sys: 11 µs, total: 78 µs
Wall time: 80.3 µs


tensor(129)

**note : built in torch methods are fast and efficient**

The most common error in the tensor multiplication is the shape error
 - for matrix multiplication:
  - the num of columns in first matrix must be equal to the number of rows in the second matrix
  - i.e inner dimensions must be equal
  - (2,3) @ (2,3) won't work
  - (3,2) @ (2,3) will work
  - (3,4) @ (4,3) => (3,3)

In [49]:
torch.matmul(torch.rand(3,4) , torch.rand(4,3))

tensor([[1.7431, 0.9866, 1.3868],
        [0.7168, 0.4046, 0.9828],
        [0.7931, 0.4767, 0.7786]])

**How to deal with shape errors in matrix multiplication**
 - take the transpose of tge any of the matrix
 - transpose means changing the axis . i.e changing rows into coulmnn or coulmns into rowns

In [50]:
tensor_A = torch.tensor([[1,5],[3,9],[8,0]])
tensor_A.shape

torch.Size([3, 2])

In [51]:
tensor_B = torch.tensor([[3,9],[9,7],[5,8]])
tensor_B.shape

torch.Size([3, 2])

In [52]:
#as inner dimensions are not equaal , it will throw an error on running

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [53]:
#in order to make the shape compatible , take the transpose of any tensor
Transpose_tensor_A= tensor_A.T  #(2,3)

In [54]:
torch.matmul(Transpose_tensor_A, tensor_B)

tensor([[ 70,  94],
        [ 96, 108]])

In [55]:
print(f"tensor_A.shape:{tensor_A.shape} and tensor_B.shape: {tensor_B.shape}")
print("inner dimensions are not equal , thus mulptication is not possible")
print(f"tensor_A.shape :{tensor_A.shape} and tensor_B.transpose.shape: {tensor_B.T.shape}")
print("inner dimensions are equal , thus mulptication is possible")
print(f"The output matrix of outer dimension shape is after matrix multipliaction = {torch.mm(tensor_A,tensor_B.T)}")

tensor_A.shape:torch.Size([3, 2]) and tensor_B.shape: torch.Size([3, 2])
inner dimensions are not equal , thus mulptication is not possible
tensor_A.shape :torch.Size([3, 2]) and tensor_B.transpose.shape: torch.Size([2, 3])
inner dimensions are equal , thus mulptication is possible
The output matrix of outer dimension shape is after matrix multipliaction = tensor([[48, 44, 45],
        [90, 90, 87],
        [24, 72, 40]])


## Tensor Aggregation
- finding the min , max , mean, sum,etc

In [56]:
rand_tensor = torch.rand(2,4)


In [57]:
#min
rand_tensor.min() , torch.min(rand_tensor)

(tensor(0.0573), tensor(0.0573))

In [58]:
#max
rand_tensor.max() , torch.max(rand_tensor)

(tensor(0.7493), tensor(0.7493))

In [59]:
#mean => mean function only works on float and complex values . As long int is given as input that's why it is throwing an error
int_values_tensor = torch.tensor([2,6,9,10],dtype=torch.int64)
# int_values_tensor.type(torch.float32).mean() #alternative method
torch.mean(int_values_tensor.type(torch.float16))

tensor(6.7500, dtype=torch.float16)

**positional min and max using argmax and argmin**

In [60]:
#argmin => will provide us the position or index of the minimum value in the given torch.tensor
new_tensor = torch.arange(2,1000,90)
new_tensor

tensor([  2,  92, 182, 272, 362, 452, 542, 632, 722, 812, 902, 992])

In [61]:
new_tensor.argmin()

tensor(0)

In [62]:
new_tensor[0] #we can find the minimum value in the tensor by using that position or index by argmin

tensor(2)

In [63]:
new_tensor.argmax() # outputs the position or index of maximum value in the tensor

tensor(11)

In [64]:
new_tensor[5]

tensor(452)

**Reshaping , stacking , sequeezing and unsequeezing tensors**

- The most common problem we encounter while working with tensors is shape incompatibility.
- To solve this error , different methods are used , some of which are as follows:
  * **Reshaping:** changing the shape of the tensor with the defined shape.
  * **view :** return a view of the input tensor in a specified shape but both the original tensor and the reshaped tensor via view are pointing to same memory location , changes in one reflects to other as well
  * **stacking** : combining the tensors in a dimention specified . By default its vertical dim=0
  * **sequeezing :** means removing the single dimension from the input array. i.e removing from double brackets to single brackets

  * **unsequeezing:**  means adding a new single dimension in the tensor i.e adding a bracket

  * **permute**: means modifying the dimensions or axis of the values in the tensors.

**reshape**()

In [65]:
x = torch.arange(2,10)
x , x.shape

(tensor([2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([8]))

In [66]:
# x_resahped = x.reshape(8,1)
# x_resahped = x.reshape(1,8)
# x_reshaped = x.reshape(2,4)
#all these are possible in which shape is comaptible
#the shape of the new modified tensor should be such way that after multiplying them , it should give the size value of the original tensor
# original tensor = 8 , new tensor can be any shape that make 8 on multiplying
x_reshaped = x.reshape(4,2)


In [67]:
print(f"original tensor is {x} with shape {x.shape}")
print("_________________________________________________")
print(f"reshaped tensor is {x_reshaped} with the shape {x_reshaped.shape}")

original tensor is tensor([2, 3, 4, 5, 6, 7, 8, 9]) with shape torch.Size([8])
_________________________________________________
reshaped tensor is tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) with the shape torch.Size([4, 2])


**view**

In [68]:
new_tensor.shape

torch.Size([12])

In [69]:
new_viewed_tensor= new_tensor.view(4,3)
new_tensor.shape


torch.Size([12])

In [70]:

print(f"new_tensor is {new_tensor} with shape {new_tensor.shape}")
print("_________________________________________________")
print(f"view of the new_tensor is {new_viewed_tensor} with shape {new_viewed_tensor.shape}")

new_tensor is tensor([  2,  92, 182, 272, 362, 452, 542, 632, 722, 812, 902, 992]) with shape torch.Size([12])
_________________________________________________
view of the new_tensor is tensor([[  2,  92, 182],
        [272, 362, 452],
        [542, 632, 722],
        [812, 902, 992]]) with shape torch.Size([4, 3])


In [71]:
new_tensor[2]=17
new_viewed_tensor[0][2]

#changes done in one also reflects in the other . this is because as both are pointing to same memory lacation

tensor(17)

**Stacking**

In [72]:
stacked_tensors = torch.stack([x,x,x],dim=1)
#dim=0 row wise stacking in vertical manner
#dim=1 column wise stacking in horizontal manner
stacked_tensors


tensor([[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

**Sequeeze**

In [73]:
Tensor = torch.tensor([[[2,9],[2,0],[4,5]]])
Tensor.shape
print(f"Before squeezing: {Tensor} with shape {Tensor.shape}")

Before squeezing: tensor([[[2, 9],
         [2, 0],
         [4, 5]]]) with shape torch.Size([1, 3, 2])


In [74]:
squeezed= torch.squeeze(Tensor)
print(f"After squeezing: {squeezed} with shape {squeezed.shape}")

After squeezing: tensor([[2, 9],
        [2, 0],
        [4, 5]]) with shape torch.Size([3, 2])


**Unsqueezing**

In [75]:
squeezed , squeezed.shape


(tensor([[2, 9],
         [2, 0],
         [4, 5]]),
 torch.Size([3, 2]))

In [76]:
unsqueezed = torch.unsqueeze(squeezed,1)
unsqueezed , unsqueezed.shape  # 0 dimension means add brackets as whole .ie. column wise ,while 1 dimension means adding bracket along each each row

(tensor([[[2, 9]],
 
         [[2, 0]],
 
         [[4, 5]]]),
 torch.Size([3, 1, 2]))

**permute**

In [77]:
x = torch.randn(2,3,5)
print(f"Before permutation: {x} with shape {x.shape}")
x.size()

print("________________________________________")
print("________________________________________")
permuted= torch.permute(x,(2,0,1)) #changing the 0->2 , 1->0 , 2->1
print(f"after permutation: {permuted} with shape {permuted.shape}")

Before permutation: tensor([[[-1.2470,  2.0676,  0.3430, -0.9086,  0.1590],
         [ 1.4641, -1.2915, -0.2005,  0.8228, -0.5582],
         [-0.1231, -0.6008,  0.6680,  0.0404,  0.4982]],

        [[ 0.3571,  0.5309, -1.9976, -0.1811,  0.4803],
         [-0.2304,  2.2584,  0.2377, -0.1559,  2.0546],
         [-0.5448, -1.1194, -0.9680, -0.1645,  1.5582]]]) with shape torch.Size([2, 3, 5])
________________________________________
________________________________________
after permutation: tensor([[[-1.2470,  1.4641, -0.1231],
         [ 0.3571, -0.2304, -0.5448]],

        [[ 2.0676, -1.2915, -0.6008],
         [ 0.5309,  2.2584, -1.1194]],

        [[ 0.3430, -0.2005,  0.6680],
         [-1.9976,  0.2377, -0.9680]],

        [[-0.9086,  0.8228,  0.0404],
         [-0.1811, -0.1559, -0.1645]],

        [[ 0.1590, -0.5582,  0.4982],
         [ 0.4803,  2.0546,  1.5582]]]) with shape torch.Size([5, 2, 3])


In [78]:
#Another example
#creating tensor for image

x_original = torch.rand(244,244,3) #height , width , colour chennels
x_permuted = torch.permute(x_original,(2,0,1)) #color chennels, height , width

x_original.shape , x_permuted.shape
#note x_original and x_permuted will share the same memory in the computer


(torch.Size([244, 244, 3]), torch.Size([3, 244, 244]))

In [79]:
#chnaging the ist value in x_orginal and then checking whether it is affecting the x_permuted or not

x_original[0,0,0]=10
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(10.), tensor(10.))

## Indexing

indexing with PyTorch are same as the indexing in NumPy

In [80]:
#creatting a tensor
x=torch.arange(1,90,8)
x.shape
x= x.reshape(1,4,3)
x

tensor([[[ 1,  9, 17],
         [25, 33, 41],
         [49, 57, 65],
         [73, 81, 89]]])

In [81]:
x[0]

tensor([[ 1,  9, 17],
        [25, 33, 41],
        [49, 57, 65],
        [73, 81, 89]])

In [82]:
x[0][0]

tensor([ 1,  9, 17])

In [83]:
x[0][0][0]

tensor(1)

In [84]:
x[0][0][2]

tensor(17)

In [85]:
x[:,:,1]

tensor([[ 9, 33, 57, 81]])

In [86]:
x[0, : ,1]

tensor([ 9, 33, 57, 81])

In [87]:
#get all the values of the 0 dimension but only 1 index value of ist and 2nd dimension

x[:,1,1]

tensor([33])

In [88]:
#get index 0 of 0th and ist diemnsion and all the values of 2nd dimension
x[0,0,:]

tensor([ 1,  9, 17])

In [89]:
#index on x to return 57
x[0,2,1]

tensor(57)

**PyTorch** **and** **NumPy**
- Numpy is the python's libraray for mathematical calculations and computations
- Tensors can be converted to numpy arrays by :
    - torch.Tensor.numpy()
- Numpy arrays can be converted into the tensors by :
    - torch.from_numpy(ndarray)

    

In [97]:
import numpy as np
import torch

#numpy array to tensors
arr = np.arange(1.,10.)
Tensor = torch.from_numpy(arr)
arr , Tensor

#by default the data type of torch is float32 and the default datatype of numpy is float64. Here the datatype of numpy array reflects to the torch

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [105]:
#by changing the array the tensor is made from , tensor will not get affected or changed
arr= arr+1
arr , Tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [104]:
#tensors to numpy
Ten1 = torch.arange(1.0,18,2)
array1 = Ten1.numpy()
array1 , Ten1
array1.dtype ,Ten1.dtype

# the datatype of the numpy array created from torch will be the same as that of the tensor


(dtype('float32'), torch.float32)

In [106]:
#by changing torch the numpy array made from from , the numpy will not be changed

Ten1 = Ten1 +1
Ten1
Ten1 , array1

(tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]),
 array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.], dtype=float32))

## Random seed
In short a neural networks leans:
start with a random numbers -> tensor operations -> update those random numbers and try to amke them better -> perform opertaions -> again -> again


Ramdon seed is very important in neural networks and pytorch as it is used to make the code or output reproducible

In pytorch we use , torch.manual_seed(42) - this flavours the randomness and make the code reproducible

In [107]:
import torch
tensor_a = torch.rand(2,4)
tensor_b = torch.rand(2,4)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)


tensor([[0.2692, 0.4002, 0.4148, 0.6661],
        [0.9923, 0.8386, 0.3149, 0.7500]])
tensor([[0.6211, 0.3668, 0.8195, 0.7363],
        [0.6087, 0.0555, 0.7699, 0.8008]])
tensor([[False, False, False, False],
        [False, False, False, False]])


In order to make the above numbers reproducible and to control the randomness , we will set the manual_seed() function before each line where there is a need to control randomness


In [116]:
#Note: if different random seed values will be passed to the manaul_seed(), it will not be reproducible.

import torch
random_seed=  42 # 42 is just a universal value or default value . it can be any integer number .

torch.manual_seed(random_seed)
tensor_a = torch.rand(2,4)

torch.manual_seed(random_seed)
tensor_b = torch.rand(2,4)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])
tensor([[True, True, True, True],
        [True, True, True, True]])


# GPU: Graphic User Interface:  
Running pytorch and tensor on the GPU to make the computations faster

GPUs = faster computations on numbers , credit goes to the CUDA , NVIDIA hardware and Pytorch running behind the scenes to make everything good

Different ways to get or use the gpus :
  - Free gpu on google colab
  - set the gpu on your own system , this need setup and investments
  -rent the divices from platforms like AWS , Azure (cloud computing)


In [14]:
!nvidia-smi

Tue Jul  8 13:15:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   67C    P0             30W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
#here in our case , we are run our tensors on the colab free gpu
#first we need to check whether gpu is present or not . in oder to do so:

import torch
torch.cuda.is_available()
#it return true , which means GPU is available

True

In [6]:
Tensor_on_cpu = torch.tensor([1,9,20])
Tensor_on_cpu.device
#by default our tensor is running on the cpu , we will set the device to gpu now


device(type='cpu')

In [3]:
#setup device agnostic code
device =  "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
#counting the number of devices
torch.cuda.device_count()

#this is needed to make a startegy that different models or tensors to run on different devices

1

In [7]:
#now that we have set the device to cpu and riiunning the tensors on GPU
#the reason we need GPU is that they are very fast on numerical calculations
# moving the tensor from cpu to gpu
#using to function to passing the tensor to the target device i.e gpu

Tensor_on_gpu = Tensor_on_cpu.to(device)
Tensor_on_gpu.device

device(type='cuda', index=0)

In [8]:
#note: numpy array only works on cpu . Thus we need to transfer the torch from gpu to cpu

Tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
 #to solve the issue , we need to fall back to cpu
 tensor_back_on_cpu = Tensor_on_gpu.cpu()


In [12]:
array_from_tensor = tensor_back_on_cpu.numpy()
array_from_tensor

array([ 1,  9, 20])